### ISSUE TITLE
PDS failure investigation

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#239]
## Problem description

GIT run on 2019/12/17 done by @PeterGhimself confirms that the that the PDS node does not start automatically as it should. Starting it manually gives us:
```
(venv) odroid@odroid:~/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts$ ./PdsNode.py uart
[INFO] [1460914926.074715]: Initialized "pds_node" node for pub/sub/service functionality
[INFO] [1460914926.075744]: Beginning to publish to "/battery_voltage" topic
[INFO] [1460914926.081042]: Begining to publish to "/wheel_motor_currents" topic
[INFO] [1460914926.086271]: Begining to publish to "/battery_temps" topic
[INFO] [1460914926.093113]: Beginning to publish to "/fan_speeds" topic
[INFO] [1460914926.099683]: Beginning to publish to "/pds_flags" topic
[INFO] [1460914926.105515]: Beginning to publish to "/pds_feedback" topic
[INFO] [1460914926.113285]: Beginning to subscribe to "/pds_command" topic
[INFO] [1460914926.122896]: Waiting for "/pds_request" service request from client
[INFO] [1460914926.129252]: Using 9600 baud by default
[INFO] [1460914926.129981]: Using UART and 9600 baud by default
[INFO] [1460914926.190084]: Attempting to connect to /dev/ttySAC0
[INFO] [1460914926.192095]: clearing buffer...
[INFO] [1460914926.194955]: identifying MCU by sending 'who' every 1000 ms
[INFO] [1460914926.195971]: attempt #1...
[INFO] [1460914927.196966]: attempt #2...
[INFO] [1460914928.198175]: attempt #3...
[INFO] [1460914929.199226]: attempt #4...
[INFO] [1460914930.200279]: attempt #5...
[ERROR] [1460914931.201367]: Incorrect MCU connected, terminating listener
```
An attempt was made with the ELEC team lead to make corrections to the UART connections on the OBC/MUX PCB but even after rewiring and confirming with the schematic it still seemed not to work.

This output seems to imply that there is a hardware connection that is not proper. This issue should be further investigated.

## Task breakdown
Starting by checking if we can get any comms at all.

- [x] Try handshakes on all mux lines switching through software
- - [x] channel 0 -> pds
- - [x] channel 1 -> pds
- - [x] channel 2 -> pds
- - [x] channel 3 -> pds

**Comment by PeterGhimself** [comment]
Did some prying with a simple trusty test script (which has been around for a while on the odroid but I never committed it, guess I'll do that now). The output seems to confirm that the odroid does not even recognize there is a UART connection available.

```
(venv) odroid@odroid:~$ rosrun mux_selector mux_select_client.py 0
Selecting MUX channel 0
2016-04-22T13:34:26-82
---
Response: Switched MUX select to device 0
s0: 1
s1: 1
2016-04-22T13:34:26-83
Latency: 9.299999999999999 ms
(venv) odroid@odroid:~$ ./test.py /dev/SAC0 9600 "PDS S"
Traceback (most recent call last):
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/SAC0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 34, in <module>
    ser = serial.Serial(port, baudrate)
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/SAC0: [Errno 2] No such file or directory: '/dev/SAC0'
(venv) odroid@odroid:~$ rosrun mux_selector mux_select_client.py 1
Selecting MUX channel 1
2016-04-22T13:34:37-83
---
Response: Switched MUX select to device 1
s0: 0
s1: 1
2016-04-22T13:34:37-85
Latency: 14.151 ms
(venv) odroid@odroid:~$ ./test.py /dev/SAC0 9600 "PDS S"
Traceback (most recent call last):
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/SAC0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 34, in <module>
    ser = serial.Serial(port, baudrate)
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/SAC0: [Errno 2] No such file or directory: '/dev/SAC0'
(venv) odroid@odroid:~$ rosrun mux_selector mux_select_client.py 2
Selecting MUX channel 2
2016-04-22T13:34:44-51
---
Response: Switched MUX select to device 2
s0: 1
s1: 0
2016-04-22T13:34:44-52
Latency: 9.639 ms
(venv) odroid@odroid:~$ ./test.py /dev/SAC0 9600 "PDS S"
Traceback (most recent call last):
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/SAC0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 34, in <module>
    ser = serial.Serial(port, baudrate)
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/SAC0: [Errno 2] No such file or directory: '/dev/SAC0'
(venv) odroid@odroid:~$ rosrun mux_selector mux_select_client.py 3
Selecting MUX channel 3
2016-04-22T13:34:50-87
---
Response: Switched MUX select to device 3
s0: 0
s1: 0
2016-04-22T13:34:50-88
Latency: 8.205 ms
(venv) odroid@odroid:~$ ./test.py /dev/SAC0 9600 "PDS S"
Traceback (most recent call last):
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/SAC0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 34, in <module>
    ser = serial.Serial(port, baudrate)
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/odroid/Programming/robotics-prototype/venv/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/SAC0: [Errno 2] No such file or directory: '/dev/SAC0'
```

**Comment by PeterGhimself** [comment]
So turns out when the last odroids ethernet port died and we switched it out for our last spare, we totally forgot to transfer over the connector/cable for the GPIO pins! Meaning the mux and serial connection have been null this whole time. I reconnected this cable and the PDSNode is running again on startup, we are getting the battery voltage feedback in the GUI even. However there are more issues I found while testing where I'm getting flaky behaviour.

Copy pasta from the GIT sections:

### Issues encountered

"The "no camera feed image" does not appear on any of the pages. PDS battery feedback appears on all pages except for Rover page probably due to js error regarding navigation panel function. The PDS commands seem to have issues, namely that cutting all power did not work and there was no feedback in the console log for the responses of the MCU. As well the indiviudal motor shutoff commands did not work as expected, they gave back feedback that would confirm that they worked but then the button states stayed ON after refresh. It was not clear that power was ever cut to motors. Also, the task handler did not start because there are some improper import statements on master which I solved in my branch simultaneous-streams-151 and confirmed that it fixed the issue by cherry picking the specific commit."

### Additional information

"All temperature values show "999" because for now we do not have the temperature sensors in place. Testing the PDS power cutting feature was not ideal. The rover was on the ground with a lot of crap underneath and around it, it should be done ideally with the rover suspended on our wooden stand made for that purpose. This specific PDS integration testing should be done again more thoroughly."

**Comment by PeterGhimself** [comment]
Following up on the last comment, the rover has been put on a stand and have tested and confirmed that the individual motor commands still work through the GUI, although not perfectly and the multi-motor commands don't work through the GUI anymore. I have opened issue #265 to address both of these concerns.

In the GIT it doesn't really make sense to do the PDS tests without the rover on a stand, since otherwise when deactivating any motor and then driving the rover on the ground there will be backdrive in other motors so it is very impractical to try to assert if the wheels are truly OFF this way. If the wheels are off the ground then you can clearly see them not moving when you deactivate specfic ones and try driving everything.
